rsa:
  private-key: classpath:certificates/private.pem
  public-key: classpath:certificates/public.pem
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: bch
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.validator.apply_to_ddl: false
      hibernate.globally_quoted_identifiers: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080
  max-http-request-header-size: 10485760